project:
  type: book

book:
  title: "Managing an open source project"
  author: "Tracy Teal"
  date: "8/29/2023"
  repo-url: https://github.com/posit-conf-2023/managing-os-project
  chapters:
    - index.qmd
    - project-goals.qmd
    - managing-expectations.qmd
    - decision-making.qmd
    - thriving.qmd
    - references.qmd
  sidebar: 
    background: "#DCE1E3"
    search: true

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - styles.scss
    number-depth: 1
  pdf:
    documentclass: scrreprt

editor: visual

