# Surviving and thriving as an open source maintainer

::: callout-tip
## Lesson objectives

In this lesson we'll discuss how to not just survive as an open source maintainer, but to thrive! We'll explore what's most important to you to make this possible, and the systems, structures and communities to connect with to help make this possible.
:::

Hopefully some of the things we've talked about already, will help you have some clarity on your goals for your project and yourself, and therefore let you have a decision making process for where and how you spend your time. That's a big part of surviving and thriving! 

It's one thing to know these things in theory though, and another to put them into practice, and most importantly make these new patterns for you or your project. 

We'll discuss some approaches you can try, have a discussion around where you've had challenges, and find shared ways to support each other. (Including if content like this is valuable)

## Approaches to try

There are a million and one books on 'habits', 'boundaries', 'self-compassion' and other related topics. There's not a new concept I can add here, and I'll share that I'm still on a journey to figuring it out myself. 

So, what I'll do is try to give you a framework for you to find your own strategies that work for you, and the resources that have resonated the most for me. My best advice is to be cautious of advice. :) People are different from each other, have intersectional identities, and different backgrounds and experiences that led them to where they are, so something that worked for someone else is not necessarily something that will be right to you. So, maybe my advice is to listen to other people's stories and what they share, and take from it what makes sense for you. I have yet to read a book or hear about someone's journey where I agreed with everything, but I almost always take away at least one thing (even if it's a 'not to do' thing).

One thing to mention though is that **you are a leader**. If you are taking this course, it means you're working on a project and learning more about supporting the project and people you work with. Often the transition is subtle, so you don't **feel** like a leader yet. But leadership isn't through title or position, it's about wanting to serve. (ok, everyone might not agree with this, but it's my definition of leadership). 

A quote I like from one of my favorite show Numb3rs is "a teacher is a leader at the front of the room". Open source maintainers are leaders in the front of the code base. Thank you for what you do.

::: callout-note
## Exercise

Where you have had challenges in a misalignment with how you decided you were going to work, with how you did? 

What are some approaches that have worked for you in aligning your goals with your actions?

:::

::: callout-note
## Exercise

What things would be useful after this workshop?

:::


### Some resources

* [Good to Great](https://www.amazon.com/Good-Great-Some-Companies-Others-ebook/dp/B0058DRUV6/) by Jim Collins
* [Wooden on Leadership](https://www.amazon.com/Wooden-Leadership-Create-Winning-Organization/dp/0071453393) by John Wooden
* [Leadership is an Art](https://www.amazon.com/Leadership-Art-Max-Depree-ebook/dp/B0053CT29A/) by Max De Pree
* [How to be a great boss](https://www.amazon.com/How-Great-Boss-Gino-Wickman-ebook/dp/B01EEQ9BVE) by Gino Wickman and René Boer 
* [15 Commitments of Concious Leadership leadership](https://www.amazon.com/15-Commitments-Conscious-Leadership-Sustainable-ebook/dp/B00R3MHWUE/) by by Jim Dethmer, Diana Chapman, Kaley Klemp 
* [Books and posts from Lara Hogan](https://larahogan.me/)
